language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t quanpa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true quanpa/docker-react npm run test